// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PH34686_THICS4.Models;

#nullable disable

namespace PH34686_THICS4.Migrations
{
    [DbContext(typeof(AppDBContext))]
    partial class AppDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("PH34686_THICS4.Models.Ca", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("DongVatID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ID_DongVat")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NoiSong")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Ten")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Tuoi")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("DongVatID");

                    b.ToTable("Cas");
                });

            modelBuilder.Entity("PH34686_THICS4.Models.DongVat", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Ho")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ThucAn")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("DongVats");
                });

            modelBuilder.Entity("PH34686_THICS4.Models.Ca", b =>
                {
                    b.HasOne("PH34686_THICS4.Models.DongVat", "DongVat")
                        .WithMany("Cas")
                        .HasForeignKey("DongVatID");

                    b.Navigation("DongVat");
                });

            modelBuilder.Entity("PH34686_THICS4.Models.DongVat", b =>
                {
                    b.Navigation("Cas");
                });
#pragma warning restore 612, 618
        }
    }
}
